"""Use Enums

Revision ID: 953b0bbe0fa6
Revises: fb2c09cc7f96
Create Date: 2026-07-10 13:13:14.551488

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '953b0bbe0fa6'
down_revision: str | Sequence[str] | None = 'fb2c09cc7f96'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

alert_level = postgresql.ENUM(
    "CRITICAL",
    "WARNING",
    "INFO",
    name="alertlevel",
)

processing_status = postgresql.ENUM(
    "UPLOADED",
    "PROCESSING",
    "PROCESSED",
    "FAILED",
    name="processingstatus",
)

scan_status = postgresql.ENUM(
    "SUSPICIOUS",
    "CLEAN",
    "FAILED",
    name="scanstatus",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    alert_level.create(op.get_bind(), checkfirst=True)
    processing_status.create(op.get_bind(), checkfirst=True)
    scan_status.create(op.get_bind(), checkfirst=True)

    op.alter_column('alerts', 'level',
               existing_type=sa.VARCHAR(length=50),
               type_=alert_level,
               existing_nullable=False,
               postgresql_using='UPPER(level)::alertlevel',
    )
    op.alter_column('files', 'processing_status',
               existing_type=sa.VARCHAR(length=50),
               type_=processing_status,
               existing_nullable=False,
               postgresql_using='UPPER(processing_status)::processingstatus',
    )
    op.alter_column('files', 'scan_status',
               existing_type=sa.VARCHAR(length=50),
               type_=scan_status,
               existing_nullable=True,
               postgresql_using='UPPER(scan_status)::scanstatus',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'scan_status',
               existing_type=scan_status,
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               postgresql_using='LOWER(scan_status::text)',
    )
    op.alter_column('files', 'processing_status',
               existing_type=processing_status,
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               postgresql_using='LOWER(processing_status::text)',
    )
    op.alter_column('alerts', 'level',
               existing_type=alert_level,
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               postgresql_using='LOWER(level::text)',
    )
    alert_level.drop(op.get_bind())
    processing_status.drop(op.get_bind())
    scan_status.drop(op.get_bind())
    # ### end Alembic commands ###
