"""Use UUID type for file IDs

Revision ID: fb2c09cc7f96
Revises: 0d6439d2e79f
Create Date: 2026-07-08 10:34:19.571922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb2c09cc7f96'
down_revision: Union[str, Sequence[str], None] = '0d6439d2e79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("alerts_file_id_fkey", "alerts", type_="foreignkey")
    op.alter_column('files', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False,
               postgresql_using="id::uuid",
    )
    op.alter_column('alerts', 'file_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False,
               postgresql_using="file_id::uuid",
    )
    op.create_foreign_key("alerts_file_id_fkey",
        source_table="alerts",
        referent_table="files",
        local_cols=["file_id"],
        remote_cols=["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("alerts_file_id_fkey", "alerts", type_="foreignkey")
    op.alter_column('files', 'id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False,
               postgresql_using="file_id::uuid",
    )
    op.alter_column('alerts', 'file_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False,
               postgresql_using="file_id::uuid",
    )
    op.create_foreign_key("alerts_file_id_fkey",
        source_table="alerts",
        referent_table="files",
        local_cols=["file_id"],
        remote_cols=["id"],
    )
    # ### end Alembic commands ###
